pref("extensions.zotodo.automatic_add", false);
pref("extensions.zotodo.ignore_collections", "");
pref("extensions.zotodo.include_note", false);
pref("extensions.zotodo.note_format", "Abstract: \"${abstract}\"");
pref("extensions.zotodo.due_string", "Today");
pref("extensions.zotodo.priority", 4);
pref("extensions.zotodo.project", "Inbox");
pref("extensions.zotodo.section", "");
pref("extensions.zotodo.set_due", false);
pref("extensions.zotodo.labels", "from_zotero");
pref("extensions.zotodo.task_format", "Read \"?${url}:[${title}](${url})?!${url}:${title}!\"");
pref("extensions.zotodo.todoist_token", "");
